.\"/*
.\" * All rights reserved
.\" *Copyright (c) [Year] [name of copyright holder]
.\" *[Software Name] is licensed under Mulan PSL v2.
.\" *You can use this software according to the terms and conditions of the Mulan PSL v2.
.\" *You may obtain a copy of Mulan PSL v2 at:
.\" *         http://license.coscl.org.cn/MulanPSL2
.\" *THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
.\" *EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
.\" *MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE. 
.\" */
.\"
.TH "keentune-param" "7" "6 May 2022" "OpenAnolis KeenTune SIG" "KeenTune"
.SH NAME
keentune-param - description of basic keentune param

.SH DESCRIPTION
The parameter is the configuration file where the target device runs with during dynamic tuning. The parameter configuration is configured in the python file for the benchmark. It corresponds to the /usr/lib/python3.6/site-packages/target/domain/ of the target environment.

.SH PARAMETER
At the moment we provide the following pre-defined parameter:

.TP
.BI "iperf.json"
For iperf3 tuning task. The test environment requires both an iperf server and a client.
.TP
.BI "nginx.json"
For nginx tuning task. The test environment requires installing nginx and starting the service.
.TP
.BI "sysctl.json"
For tuning for operating system configuraions.
.TP
.BI "fio.json"
For tuning hard disk data processing with the metric of IOPS. The test environment requires installing fio.
.TP
.BI "sysbench.json"
For tuning the performance of MySQL database.

.SH FILES
.I /etc/keentune/parameter/

.SH "SEE ALSO"
.LP
keentune(8)

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
