.\"/*
.\" * All rights reserved
.\" *Copyright (c) [Year] [name of copyright holder]
.\" *[Software Name] is licensed under Mulan PSL v2.
.\" *You can use this software according to the terms and conditions of the Mulan PSL v2.
.\" *You may obtain a copy of Mulan PSL v2 at:
.\" *         http://license.coscl.org.cn/MulanPSL2
.\" *THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
.\" *EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
.\" *MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE. 
.\" */
.\"
.TH "keentune-detect" "7" "6 May 2022" "OpenAnolis KeenTune SIG" "KeenTune"
.SH NAME
keentune-detect - description of basic keentune detect

.SH DESCRIPTION
Detect the hardware information of the target machine. For example, the number of cpu and the memory size.

.SH DETECT
At the moment we provide the following pre-defined detect:

.TP
.BI "detect.json"
Contains the command to query the number of cpu or the memory size.

.SH "EXAMPLE"
.nf
"cpu_core":"cat /proc/cpuinfo | grep process | wc -l"
"mem_size":"free -m | awk 'NR==2' | awk '{print $2}'"

.SH "FILES"
.I /etc/keentune/detect/

.SH "SEE ALSO"
.LP
keentune(8)

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
