.TH "keentuned.conf" "5" "5 May 2022" "KeenTune"
.SH NAME
keentuned.conf - keentuned configuration file
.SH SYNOPSIS
.B /etc/keentune/conf/keentuned.conf
.SH DESCRIPTION
This man page documents the format of the keentuned configuration file.
The \fIkeentuned.conf\fR file uses the ini\-file format.
.
.SH "[keentuned]"
Attributes used in KeenTuned
.
.TP
\fBKEENTUNED_HOME = /etc/keentune\fR
KeenTuned depository location
.
.TP
\fBPORT = 9871\fR
KeenTuned access port
.
.TP
\fBHEARTBEAT_TIME = 30\fR
Heartbeat detection interval(unit: seconds), recommended value 30
.
.TP
\fBDUMP_HOME = /var/keentune\fR
Dump home is the working directory for KeenTune job execution result
.
.TP
\fBDUMP_BASELINE_CONFIGURATION = false\fR
\fBDUMP_TUNING_CONFIGURATION = false\fR
\fBDUMP_BEST_CONFIGURATION = true\fR
Configuration about configuration dumping
.
.TP
\fBBASELINE_BENCH_ROUND = 5\fR
Benchmark execution rounds of baseline
.
.TP
\fBTUNING_BENCH_ROUND = 3\fR
Benchmark execution rounds during tuning exection
.
.TP
\fBRECHECK_BENCH_ROUND = 4\fR
Benchmark execution rounds after tuning for recheck
.
.TP
\fBLOGFILE_LEVEL = DEBUG\fR
Logfile log level, i.e. INFO, DEBUG, WARN, FATAL
.
.TP
\fBLOGFILE_NAME = keentuned.log\fR
Logfile name
.
.TP
\fBLOGFILE_INTERVAL = 2\fR
Logfile interval
.
.TP
\fBLOGFILE_BACKUP_COUNT = 14\fR
Logfile backup count
.
.SH "[brain]"
Attributes used to connect the brain environment
.
.TP
\fBBRAIN_IP = localhost\fR
Brain machine ip
.
.TP
\fBBRAIN_PORT = 9872\fR
Brain machine access port
.
.TP
\fBAUTO_TUNING_ALGORITHM = tpe\fR
\fBSENSITIZE_ALGORITHM = shap\fR
Brain optimization algorithm. available algorithms: tpe, hord, random
.
.SH "[target-group-1]"
Attributes used to connect the target group environment
.
.TP
\fBTARGET_IP = localhost\fR
Target tuned machine ips, e.g. "ip1,ip2,...,ipn". Multiple groups TARGET_IP cannot be duplicated
.
.TP
\fBTARGET_PORT = 9873\fR
Target tuned machine access port
.
.TP
\fBPARAMETER = sysctl.json\fR
.
.SH "[bench-group-1]"
Attributes used to connect the benchmark environment
.
.TP
\fBBENCH_SRC_IP = localhost\fR
\fBBENCH_DEST_IP = localhost\fR
Benchmark machine ip
.
.TP
\fBBENCH_SRC_PORT = 9874\fR
Benchmark machine access port
.
.TP
\fBBENCH_CONFIG = wrk_http_long.json\fR
.
.SH FILES
.I /etc/keentune/conf/keentuned.conf

.SH "SEE ALSO"
.LP
keentune(8)

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
