.\"/*
.\" * All rights reserved
.\" *Copyright (c) [Year] [name of copyright holder]
.\" *[Software Name] is licensed under Mulan PSL v2.
.\" *You can use this software according to the terms and conditions of the Mulan PSL v2.
.\" *You may obtain a copy of Mulan PSL v2 at:
.\" *         http://license.coscl.org.cn/MulanPSL2
.\" *THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
.\" *EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
.\" *MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
.\" */
.\".
.TH "keentuned" "8" "5 May 2022" "OpenAnolis KeenTune SIG" "KeenTune"
.SH NAME
KeenTuned - system performance tuning daemon
.SH SYNOPSIS
\fBKeenTuned\fP
.SH DESCRIPTION
\fBKeenTuned\fR KeenTuned is the management component of KeenTune, including CLI and Daemon. CLI provides command line interfaces to users, which includes three kinds of commands: basic commands, static tuning related commands, and dynamic tuning related commands. Keentuned，as the management and control module, is responsible for monitoring other components, receiving and parsing commands from CLI, and scheduling related components in workflows.

.SH "Run"
.
.TP
\fBsystemctl start keentuned.service\fR

.SH "BUGS"
Report bugs at: https://gitee.com/anolis/keentuned/issues
                                                                                                                                                                                                1,1          顶端
